---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adot-ao-metrictrace-os
rules:
- apiGroups: [""]
  resources:
  - nodes
  - nodes/proxy
  - nodes/metrics
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adot-ao-metrictrace-os
subjects:
- kind: ServiceAccount
  namespace: adot-collector
  name: adot-ao-metrictrace-os
roleRef:
  kind: ClusterRole
  name: adot-ao-metrictrace-os
  apiGroup: rbac.authorization.k8s.io
