apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: Opaque
data:
  KC_HOSTNAME: a2V5Y2xvYWsuaW5zcGlyZS13YXIuc2hvcA==
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: MXFhMndzIUA=
  KC_DB: a2V5Y2xvYWs=
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vaGNzLXBvYy1yZHMta2V5Y2xvYWstcG9jLmNqaXFmOGFqbDh4dS5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbS9rZXljbG9haw==
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_DB_PASSWORD: MXFhMndzIVA=
