kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-readonly-binding
subjects:
  - kind: User
    name: cluster_solutions_architect
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-readonly-role
  apiGroup: rbac.authorization.k8s.io
