apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: readonly-clusterrole
rules:
  - apiGroups: [
        "",
        "apps",
        "batch",
        "extensions",
        "networking.k8s.io",
        "storage.k8s.io",
      ] # 필요한 API 그룹 추가
    resources: [
        "pods",
        "services",
        "deployments",
        "nodes",
        "namespaces",
        "ingresses",
        "persistentvolumeclaims",
        "configmaps",
        "secrets",
        "jobs",
        "cronjobs",
        "statefulsets",
        "daemonsets",
        "replicasets",
      ] # 필요한 리소스 추가
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics", "/healthz", "/version"] # 필요시 비-리소스 URL 접근 허용
    verbs: ["get"]
