---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak
  namespace: keycloak
type: Opaque
data:
  KC_HOSTNAME: a2V5Y2xvYWsuaW5zcGlyZS13YXIuc2hvcA==
  KEYCLOAK_ADMIN: YWRtaW4=
  KEYCLOAK_ADMIN_PASSWORD: MXFhMndzIUA=
  KC_DB: a2V5Y2xvYWs=
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vaGNzLXBvYy1yZHMta2V5Y2xvYWstcG9jLmNqaXFmOGFqbDh4dS5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbS9rZXljbG9haw==
  KC_DB_USERNAME: a2V5Y2xvYWs=
  KC_DB_PASSWORD: MXFhMndzIVA=
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
  namespace: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.3
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: DB_VENDOR
              #value: mysql
              value: POSTGRES
            - name: DB_ADDR
              value: "jdbc:postgresql://hcs-poc-rds-keycloak-poc.cjiqf8ajl8xu.ap-northeast-2.rds.amazonaws.com/keycloak"
            - name: DB_USERNAME
              value: "keycloak"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KC_DB_PASSWORD
            - name: DB_PORT
              value: "5432"
            - name: DB_DATABASE
              value: "keycloak"
            - name: KC_PROXY
              value: "edge"
            #- name: jgroups.dns.query
            #value: keycloak
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    #kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #alb.ingress.kubernetes.io/backend-protocol: HTTPS
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/load-balancer-name: keycloak-alb-ingress
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/success-codes: "200-399"
    external-dns.alpha.kubernetes.io/hostname: "keycloak.inspire-war.shop"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:446805103418:certificate/e93c75b9-7009-42c3-9aae-93cd5083be2a
  labels:
    app: keycloak
spec:
  ingressClassName: alb
  tls:
    - hosts:
        - "keycloak.inspire-war.shop"
  rules:
    - host: "keycloak.inspire-war.shop"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak
                port:
                  number: 8080
---

