apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: hcs-blue-eks-cluster
  region: ap-northeast-2

identityProviders:
  - name: keycloak-provider
    type: oidc
    issuerUrl: https://keycloak.inspire-war.shop/realms/hcs-poc
    clientId: kuberntes-client
    usernameClaim: preferred_username
    #usernamePrefix: -
    groupsClaim: groups
    groupsPrefix: "kubernetes:"
    #groupsPrefix: "system:"
    requiredClaims:
      string: string
    # tags:
    #   env: poc
